name: agenda_academica_frontend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
# Autenticación y Base de Datos
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  
  # Gestión de Estado y Variables de Entorno
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  
  # Tipografía y Diseño
  google_fonts: ^6.2.1
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  
  # Gráficos y Visualización
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  
  # Firebase AI Logic (Gemini)
  firebase_ai: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  assets:
    - .env
    - assets/logo/

  uses-material-design: true

